- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Check if index.html is exist
  delegate_to: localhost
  stat:
    # path: /home/bilal/office/seal/live-demo/ansible/dynamic-inventory/roles/my_nginx/templates/index.html # correct path
    path: /home/bilal/office/seal/live-demo/ansible/dynamic-inventory/wdawa/my_nginx/templates/index.html # wrong path
  register: is_html_exist

# - name: Display output
#   ansible.builtin.debug:
#     msg: "{{ is_html_exist.stat.mimetype }}"
# - name: Display output
#   ansible.builtin.debug:
#     msg: "{{ is_html_exist.stat.exists }}"

- name: Make webpage
  when: is_html_exist.stat.exists and is_html_exist.stat.mimetype == "text/html"
  # ignore_errors: true
  ansible.builtin.copy:
    src: ../templates/index.html
    dest: /var/www/html/index.html
    ## bisa juga pake kaya gini
    # content: |
    #   <html>
    #     <h1>testing</h1>
    #   </html>

- name: Restart Nginx Service
  when: is_html_exist.stat.exists and is_html_exist.stat.mimetype == "text/html"
  service:
    name: nginx
    state: restarted
    enabled: true
